set(SUBGROUP_PATH .)
set(GITHUB_ORGANIZATION OpenCMISS)

SET(IRON_CMAKE_ARGS ${COMPONENT_COMMON_DEFS})
	LIST(APPEND IRON_CMAKE_ARGS
	    -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
	    -DCMAKE_PREFIX_PATH=${OPENCMISS_DEPENDENCIES_INSTALL_PREFIX}/lib/cmake
	)
	# iron will include config directly?! (later)
	if (MPI_HOME)
        LIST(APPEND IRON_CMAKE_ARGS
            -DMPI_HOME=${MPI_HOME}
        )
    endif()
	
    SET(IRON_BINARY_DIR ${OPENCMISS_IRON_DIR}/build/${ARCHITECTURE_PATH})
    GET_BUILD_COMMANDS(BUILD_COMMAND INSTALL_COMMAND ${IRON_BINARY_DIR} TRUE)
    ExternalProject_Add(IRON 
        DEPENDS DEPENDENCIES
        PREFIX ${OPENCMISS_IRON_DIR}
		TMP_DIR ${IRON_BINARY_DIR}/ep_tmp
		STAMP_DIR ${IRON_BINARY_DIR}/ep_stamp
		#--Download step--------------
		DOWNLOAD_DIR ${IRON_BINARY_DIR}/ep_dl
        ${USERMODE_DOWNLOAD_CMDS}
		#--Configure step-------------
		CMAKE_COMMAND ${CMAKE_COMMAND} --no-warn-unused-cli
		SOURCE_DIR ${OPENCMISS_IRON_DIR}
		BINARY_DIR ${IRON_BINARY_DIR}
		CMAKE_ARGS ${IRON_CMAKE_ARGS}
		#--Build step-----------------
		BUILD_COMMAND ${BUILD_COMMAND}
		#--Install step---------------
		INSTALL_COMMAND ${INSTALL_COMMAND}
	)
	#if (OCM_DEVELOPER_MODE)
	#    ADD_SUBMODULE_CHECKOUT_STEPS(IRON ${OpenCMISS_SOURCE_DIR} iron NO)
    #endif()