# Some shipped find-package modules have a different case-sensitive spelling - need to stay consistent with that
SET(LIBXML2_CASENAME LibXml2)

# Generate the wrappers (if not existing)
SET(WRAPPER_DIR ${OPENCMISS_MANAGE_DIR}/CMakeFindModuleWrappers)
foreach(PACKAGE_NAME ${PACKAGES_WITH_TARGETS})
    # See above
    if (${PACKAGE_NAME}_CASENAME)
        SET(PACKAGE_CASENAME ${${PACKAGE_NAME}_CASENAME})
    else()
        SET(PACKAGE_CASENAME ${PACKAGE_NAME})
    endif()
    SET(FILE ${WRAPPER_DIR}/Find${PACKAGE_CASENAME}.cmake)
    #if(NOT EXISTS ${FILE})
        SET(PACKAGE_TARGETS ${${PACKAGE_NAME}_TARGETS})
        configure_file(${WRAPPER_DIR}/FindXXX.in.cmake ${FILE} @ONLY)
    #endif()
endforeach()

# Fortran mangling - only detect if not already set manually.
if (NOT FORTRAN_MANGLING)
    include(FortranCInterface)
    FortranCInterface_VERIFY()
    FortranCInterface_VERIFY(CXX)
    if (FortranCInterface_GLOBAL_SUFFIX STREQUAL _ AND FortranCInterface_GLOBAL_CASE STREQUAL LOWER)
        SET(FORTRAN_MANGLING Add_)
    elseif(FortranCInterface_GLOBAL_SUFFIX STREQUAL "" AND FortranCInterface_GLOBAL_CASE STREQUAL UPPER)
        SET(FORTRAN_MANGLING UpCase)
    endif()
    if (NOT FORTRAN_MANGLING)
        message(FATAL_ERROR "Fortran mangling autodetection: case not implemented yet: Suffix '${FortranCInterface_GLOBAL_SUFFIX}', Case '${FortranCInterface_GLOBAL_CASE}'")
    endif()
endif()
