set(EXPORT_VARS 
    CMAKE_C_COMPILER CMAKE_CXX_COMPILER CMAKE_Fortran_COMPILER
    CMAKE_C_FLAGS CMAKE_CXX_FLAGS CMAKE_Fortran_FLAGS
    CMAKE_C_FLAGS_RELEASE CMAKE_CXX_FLAGS_RELEASE CMAKE_Fortran_FLAGS_RELEASE
    CMAKE_C_FLAGS_DEBUG CMAKE_CXX_FLAGS_DEBUG CMAKE_Fortran_FLAGS_DEBUG
    MPI_C_COMPILER MPI_CXX_COMPILER MPI_Fortran_COMPILER
    MPI MPI_HOME
    FORTRAN_MANGLING BUILD_SHARED_LIBS
    CMAKE_POSITION_INDEPENDENT_CODE
    OPENCMISS_PREFIX_PATH
    OCM_USE_MT OCM_USE_MPI OCM_SYSTEM_MPI)

set(CFILE ${OPENCMISS_COMPONENTS_INSTALL_PREFIX}/OpenCMISSBuildContext.cmake)
file(WRITE ${CFILE} "#Exported OpenCMISS configuration\r\n")
foreach(VARNAME ${EXPORT_VARS})
    if (DEFINED ${VARNAME})
        file(APPEND ${CFILE} "set(${VARNAME} ${${VARNAME}})\r\n")  
    endif()    
endforeach()
unset(EXPORT_VARS)
unset(CFILE)