include(DependenciesTargets)
SET(WRAPPER_DIR ${OpenCMISS_Utilities_SOURCE_DIR}/CMakeFindModuleWrappers)
foreach(PACKAGE_NAME ${PACKAGES_WITH_TARGETS})
    SET(FILE ${WRAPPER_DIR}/Find${PACKAGE_NAME}.cmake)
    #if(NOT EXISTS ${FILE})
        SET(PACKAGE_TARGETS ${${PACKAGE_NAME}_TARGETS})
        configure_file(${WRAPPER_DIR}/FindXXX.in.cmake ${FILE} @ONLY)
    #endif()
endforeach()