make_directory(${CONFIG_PATH})
execute_process(
    COMMAND ${CMAKE_COMMAND} -DTOOLCHAIN=${OPENCMISS_TOOLCHAIN} -DMPI=${OPENCMISS_MPI} -DOPENCMISS_CMAKE_MODULES_PATH=${OPENCMISS_CMAKE_MODULES_PATH} -DOPENCMISS_ROOTS_FILE=${CONFIGURED_FILES_DIR}/OpenCMISSRoots.cmake -DMANAGE_MODULE_PATH=${MANAGE_MODULE_PATH} ${CMAKE_CURRENT_SOURCE_DIR}/config
    WORKING_DIRECTORY ${CONFIG_PATH}
    )
