make_directory(${CONFIG_PATH})
execute_process(
    COMMAND ${CMAKE_COMMAND} -DOPENCMISS_MODULE_PATH=${OPENCMISS_MODULE_PATH} -DOPENCMISS_ROOT=${OPENCMISS_ROOT} ${CMAKE_CURRENT_SOURCE_DIR}/config
    WORKING_DIRECTORY ${CONFIG_PATH}
    )
