# Do not change the values in these files.

set(OPENCMISS_ZINC_SOURCE_DIR @OPENCMISS_ZINC_ROOT@/src)
set(OPENCMISS_ZINC_BINARY_DIR @OPENCMISS_ZINC_ROOT@/build${ARCHITECTURE_NO_MPI_PATH})
set(OPENCMISS_ZINC_INSTALL_PREFIX @OPENCMISS_ZINC_ROOT@/install${ARCHITECTURE_NO_MPI_PATH})

set(OPENCMISS_IRON_SOURCE_DIR @OPENCMISS_IRON_ROOT@/src)
set(OPENCMISS_IRON_BINARY_DIR @OPENCMISS_IRON_ROOT@/build${ARCHITECTURE_MPI_PATH})
set(OPENCMISS_IRON_INSTALL_PREFIX @OPENCMISS_IRON_ROOT@/install${ARCHITECTURE_MPI_PATH})
