
set(OPENCMISS_DEPENDENCIES_SOURCE_DIR @OPENCMISS_ROOT@/src/dependencies)
set(OPENCMISS_DEPENDENCIES_BINARY_MPI_DIR @OPENCMISS_ROOT@/build/${OPENCMISS_ARCHITECTURE_MPI_PATH}/dependencies)
set(OPENCMISS_DEPENDENCIES_BINARY_NOMPI_DIR @OPENCMISS_ROOT@/build/${OPENCMISS_ARCHITECTURE_NOMPI_PATH}/dependencies)
set(OPENCMISS_DEPENDENCIES_INSTALL_ROOT @OPENCMISS_ROOT@/install)

set(OPENCMISS_LIBRARIES_SOURCE_DIR @OPENCMISS_ROOT@/src)
set(OPENCMISS_LIBRARIES_BINARY_MPI_DIR @OPENCMISS_ROOT@/build/${OPENCMISS_ARCHITECTURE_MPI_PATH})
set(OPENCMISS_LIBRARIES_BINARY_NOMPI_DIR @OPENCMISS_ROOT@/build/${OPENCMISS_ARCHITECTURE_NOMPI_PATH})
set(OPENCMISS_LIBRARIES_INSTALL_ROOT @OPENCMISS_ROOT@/install)

set(OPENCMISS_CMAKE_MODULES_SOURCE_DIR @OPENCMISS_ROOT@/src/cmake_modules)
set(OPENCMISS_CMAKE_MODULES_BINARY_DIR @OPENCMISS_ROOT@/build/cmake_modules)
set(OPENCMISS_CMAKE_MODULES_PATH @OPENCMISS_ROOT@/install/share/cmake)

