
set(OPENCMISS_DEPENDENCIES_ROOT ${OPENCMISS_ROOT})
set(OPENCMISS_DEPENDENCIES_INSTALL_ROOT ${OPENCMISS_ROOT}/install)

set(OPENCMISS_LIBRARIES_ROOT ${OPENCMISS_ROOT})
set(OPENCMISS_LIBRARIES_INSTALL_ROOT ${OPENCMISS_ROOT}/install)

set(OPENCMISS_CMAKE_MODULES_ROOT ${OPENCMISS_ROOT})
set(OPENCMISS_CMAKE_MODULES_PATH ${OPENCMISS_ROOT}/install/share/cmake)
