# Do not change the values in these files.

set(OPENCMISS_DEPENDENCIES_SOURCE_DIR @OPENCMISS_DEPENDENCIES_ROOT@/src)
set(OPENCMISS_DEPENDENCIES_BINARY_MPI_DIR @OPENCMISS_DEPENDENCIES_ROOT@/build${ARCHITECTURE_MPI_PATH})
set(OPENCMISS_DEPENDENCIES_BINARY_NO_MPI_DIR @OPENCMISS_DEPENDENCIES_ROOT@/build${ARCHITECTURE_NO_MPI_PATH})
set(OPENCMISS_DEPENDENCIES_INSTALL_MPI_PREFIX @OPENCMISS_DEPENDENCIES_ROOT@/install${ARCHITECTURE_MPI_PATH})
set(OPENCMISS_DEPENDENCIES_INSTALL_NO_MPI_PREFIX @OPENCMISS_DEPENDENCIES_ROOT@/install${ARCHITECTURE_NO_MPI_PATH})

