set(OPENCMISS_DEPENDENCIES_ROOT ${OPENCMISS_DEPENDENCIES_ROOT})
set(OPENCMISS_DEPENDENCIES_INSTALL_ROOT ${OPENCMISS_DEPENDENCIES_ROOT}/install)

set(OPENCMISS_LIBRARIES_ROOT ${OPENCMISS_LIBRARIES_ROOT})
set(OPENCMISS_LIBRARIES_INSTALL_ROOT ${OPENCMISS_LIBRARIES_ROOT}/install)

set(OPENCMISS_CMAKE_MODULES_ROOT ${OPENCMISS_CMAKE_MODULES_ROOT})
set(OPENCMISS_CMAKE_MODULES_PATH ${OPENCMISS_CMAKE_MODULES_ROOT}/install/share/cmake)
