
set(OPENCMISS_DEPENDENCIES_SOURCE_DIR @OPENCMISS_DEPENDENCIES_ROOT@/src)
set(OPENCMISS_DEPENDENCIES_BINARY_MPI_DIR @OPENCMISS_DEPENDENCIES_ROOT@/build/${OPENCMISS_ARCHITECTURE_MPI_PATH})
set(OPENCMISS_DEPENDENCIES_BINARY_NOMPI_DIR @OPENCMISS_DEPENDENCIES_ROOT@/build/${OPENCMISS_ARCHITECTURE_NOMPI_PATH})
set(OPENCMISS_DEPENDENCIES_INSTALL_ROOT @OPENCMISS_DEPENDENCIES_ROOT@/install)

set(OPENCMISS_LIBRARIES_SOURCE_DIR @OPENCMISS_LIBRARIES_ROOT@/src)
set(OPENCMISS_LIBRARIES_BINARY_MPI_DIR @OPENCMISS_LIBRARIES_ROOT@/build/${OPENCMISS_ARCHITECTURE_MPI_PATH})
set(OPENCMISS_LIBRARIES_BINARY_NOMPI_DIR @OPENCMISS_LIBRARIES_ROOT@/build/${OPENCMISS_ARCHITECTURE_NOMPI_PATH})
set(OPENCMISS_LIBRARIES_INSTALL_ROOT @OPENCMISS_LIBRARIES_ROOT@/install)

set(OPENCMISS_CMAKE_MODULES_SOURCE_DIR @OPENCMISS_CMAKE_MODULES_ROOT@/src)
set(OPENCMISS_CMAKE_MODULES_BINARY_DIR @OPENCMISS_CMAKE_MODULES_ROOT@/build)
set(OPENCMISS_CMAKE_MODULES_PATH @OPENCMISS_CMAKE_MODULES_ROOT@/install/share/cmake)

