
set(OPENCMISS_DEPENDENCIES_SOURCE_DIR @OPENCMISS_DEPENDENCIES_ROOT@/src)
set(OPENCMISS_DEPENDENCIES_BINARY_MPI_DIR @OPENCMISS_DEPENDENCIES_ROOT@/build/${ARCHITECTURE_MPI_PATH})
set(OPENCMISS_DEPENDENCIES_BINARY_NO_MPI_DIR @OPENCMISS_DEPENDENCIES_ROOT@/build/${ARCHITECTURE_NO_MPI_PATH})
set(OPENCMISS_DEPENDENCIES_INSTALL_MPI_PREFIX @OPENCMISS_DEPENDENCIES_ROOT@/install/${ARCHITECTURE_MPI_PATH})
set(OPENCMISS_DEPENDENCIES_INSTALL_NO_MPI_PREFIX @OPENCMISS_DEPENDENCIES_ROOT@/install/${ARCHITECTURE_NO_MPI_PATH})

set(OPENCMISS_LIBRARIES_SOURCE_DIR @OPENCMISS_LIBRARIES_ROOT@/src)
set(OPENCMISS_LIBRARIES_BINARY_MPI_DIR @OPENCMISS_LIBRARIES_ROOT@/build/${ARCHITECTURE_MPI_PATH})
set(OPENCMISS_LIBRARIES_BINARY_NO_MPI_DIR @OPENCMISS_LIBRARIES_ROOT@/build/${ARCHITECTURE_NO_MPI_PATH})
set(OPENCMISS_LIBRARIES_INSTALL_MPI_PREFIX @OPENCMISS_LIBRARIES_ROOT@/install/${ARCHITECTURE_MPI_PATH})
set(OPENCMISS_LIBRARIES_INSTALL_NO_MPI_PREFIX @OPENCMISS_LIBRARIES_ROOT@/install/${ARCHITECTURE_NO_MPI_PATH})

set(OPENCMISS_CMAKE_MODULES_SOURCE_DIR @OPENCMISS_CMAKE_MODULES_ROOT@/src)
set(OPENCMISS_CMAKE_MODULES_BINARY_DIR @OPENCMISS_CMAKE_MODULES_ROOT@/build)
set(OPENCMISS_CMAKE_MODULE_PATH @OPENCMISS_CMAKE_MODULES_ROOT@/install/share/cmake)

