
# Don't show the variables in this file in a GUI by making them cache variables, they should be invariant 
# for configured builds.

set(OPENCMISS_DEVELOP_ALL ${OPENCMISS_DEVELOP_ALL})
set(OPENCMISS_USE_ARCHITECTURE_PATH ${OPENCMISS_USE_ARCHITECTURE_PATH})
set(OPENCMISS_ROOTS_FILE ${CONFIGURED_FILES_DIR}/OpenCMISSRoots.cmake)
set(OPENCMISS_SUPPORT_DIR ${SUPPORT_DIR})
set(OPENCMISS_INSTALLATION_SUPPORT_EMAIL ${OPENCMISS_INSTALLATION_SUPPORT_EMAIL})
