# Do not change the values in these files.

set(OPENCMISS_EXAMPLES_SOURCE_DIR @OPENCMISS_ROOT@/src/examples)
set(OPENCMISS_EXAMPLES_BINARY_MPI_DIR @OPENCMISS_ROOT@/build${ARCHITECTURE_MPI_PATH}/examples)
set(OPENCMISS_EXAMPLES_BINARY_NO_MPI_DIR @OPENCMISS_ROOT@/build${ARCHITECTURE_NO_MPI_PATH}/examples)
set(OPENCMISS_EXAMPLES_INSTALL_MPI_PREFIX @OPENCMISS_ROOT@/install${ARCHITECTURE_MPI_PATH})
set(OPENCMISS_EXAMPLES_INSTALL_NO_MPI_PREFIX @OPENCMISS_ROOT@/install${ARCHITECTURE_NO_MPI_PATH})

set(OPENCMISS_DEPENDENCIES_SOURCE_DIR @OPENCMISS_ROOT@/src/dependencies)
set(OPENCMISS_DEPENDENCIES_BINARY_MPI_DIR @OPENCMISS_ROOT@/build${ARCHITECTURE_MPI_PATH}/dependencies)
set(OPENCMISS_DEPENDENCIES_BINARY_NO_MPI_DIR @OPENCMISS_ROOT@/build${ARCHITECTURE_NO_MPI_PATH}/dependencies)
set(OPENCMISS_DEPENDENCIES_INSTALL_MPI_PREFIX @OPENCMISS_ROOT@/install${ARCHITECTURE_MPI_PATH})
set(OPENCMISS_DEPENDENCIES_INSTALL_NO_MPI_PREFIX @OPENCMISS_ROOT@/install${ARCHITECTURE_NO_MPI_PATH})

set(OPENCMISS_LIBRARIES_SOURCE_DIR @OPENCMISS_ROOT@/src)
set(OPENCMISS_LIBRARIES_BINARY_MPI_DIR @OPENCMISS_ROOT@/build${ARCHITECTURE_MPI_PATH})
set(OPENCMISS_LIBRARIES_BINARY_NO_MPI_DIR @OPENCMISS_ROOT@/build${ARCHITECTURE_NO_MPI_PATH})
set(OPENCMISS_LIBRARIES_INSTALL_MPI_PREFIX @OPENCMISS_ROOT@/install${ARCHITECTURE_MPI_PATH})
set(OPENCMISS_LIBRARIES_INSTALL_NO_MPI_PREFIX @OPENCMISS_ROOT@/install${ARCHITECTURE_NO_MPI_PATH})

