# Check for C++11 capability.
if((MSVC AND NOT MSVC_VERSION VERSION_LESS 1600) OR
   (CMAKE_COMPILER_IS_GNUCXX AND NOT CMAKE_CXX_COMPILER_VERSION VERSION_LESS 4.6) OR
   (CMAKE_CXX_COMPILER_ID STREQUAL "Clang" AND NOT CMAKE_CXX_COMPILER_VERSION VERSION_LESS 3.1) OR
   (CMAKE_CXX_COMPILER_ID STREQUAL "Intel" AND NOT CMAKE_CXX_COMPILER_VERSION VERSION_LESS 12.1) OR
   (CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang" AND NOT CMAKE_CXX_COMPILER_VERSION VERSION_LESS 3.1))
    set(OC_HAVE_CXX11_CAPABLE_COMPILER TRUE)
else()
    set(OC_HAVE_CXX11_CAPABLE_COMPILER FALSE)
endif()
